### PR TITLE
Improved Files Interface

### PR DESCRIPTION
**Pull request by pfrazee**
screen shot 2016-10-03 at 3 20 19 pm

For performance and usability improvements, this PR will remove the `view-dat:` protocol, and instead use pages builtin to the `beaker:` protocol.

Still todo:

- [x] Loading view
- [x] Error view
- [ ] Responsive styles
- [x] Empty beaker:archives view
- [x] Replace all view-dat: links
- [x] Remove all view-dat code and builtin interface from the dat plugin.
- [ ] Change beaker: from a file protocol to a request/response protocol, which will allow consistent CSP headers, drag-drop behaviors (currently broken on the archive view), and other dynamic behaviors (which is a future requirement).

### CODE REVIEW

**Comment by fredhampton** [comment]
Does this mean that Beaker will no longer use dat ?
Is the change to request/response protocol being done to allow for app/eco system development?

Thanks

**Comment by pfrazee** [comment]
> Does this mean that Beaker will no longer use dat ?

No, we're still using dat. In the current master, Beaker has two dat-related protocols, `dat://` and `view-dat://`. The `view-dat` protocol lets you view the files inside of a dat. This change will get rid of the `view-dat` protocol, and instead integrate its UI into the `beaker:` protocol, which serves the browser's builtin interfaces.

> Is the change to request/response protocol being done to allow for app/eco system development?

Yes, though those plans aren't set in stone yet. In the future, I'm hoping that requests to the `beaker:` URLs will be able to give interesting information and controls to the browser's resources.

**Comment by fredhampton** [comment]
GREAT !!!


Thanks !!


On October 3, 2016 at 4:21:17 PM, Paul Frazee (notifications@github.com) wrote:

Does this mean that Beaker will no longer use dat ?

No, we're still using dat. In the current master, Beaker has two dat-related protocols, dat:// and view-dat://. The view-dat protocol lets you view the files inside of a dat. This change will get rid of the view-dat protocol, and instead integrate its UI into the beaker: protocol, which serves the browser's builtin interfaces.

Is the change to request/response protocol being done to allow for app/eco system development?

Yes, though those plans aren't set in stone yet. In the future, I'm hoping that requests to the beaker: URLs will be able to give interesting information and controls to the browser's resources.

**Comment by pfrazee** [comment]
Going to go ahead and merge. Responsive styles are still todo, as is fixing the dragdrop. (I'll file an issue for the dragdrop.) I need more time to think about the responsive issue.

**Pull request merged**
