### PR TITLE
Favicon Drawing Tool #1206

### PR DESCRIPTION
**Pull request by Septimus**
- Added feature for drawing custom favicons from inside Beaker
- Supports 16x16 and 32x32 favicons
- 48 color static palette
- 256x256 drawing space (grid)
- Basic tools: Eraser and Clear Canvas

### CODE REVIEW

**Comment by pfrazee** [comment]
Coming along great! PRed some updates here: https://github.com/Septimus/beaker/pull/2

Still todo:

 - [ ] PR the beaker-core changes
 - [ ] We should output the same resolution favicon every time. If the user draws in a lower res (e.g. 8x8) we should just scale the pixels up to the target resolution. That will make it look pixel-arty
 - [ ] The favicon drawing tools' preview space needs a border around it so the user isn't surprised when it shows up

👍 👍 👍

**Comment by pfrazee** [comment]
👍 Merging! Great work @Septimus !

I added the ability for the editor to load the current favicon, so that you can edit the current instead of starting fresh every time

**Comment by todrobbins** [comment]
http://78.media.tumblr.com/d84344e8cc848accb47a29ec5849869a/tumblr_n1eqnyk4p51r2tuixo1_400.gif

`git pull`

**Comment by pfrazee** [comment]
@todrobbins haha what's up?

**Comment by todrobbins** [comment]
Just excited to rebuild with this live!

**Pull request merged**
