### PR TITLE
Dockable devtools (WIP)

### PR DESCRIPTION
**Pull request by pfrazee**
Closes https://github.com/beakerbrowser/beaker/issues/145

Todos:

 - [x] Merge electron v2 update (separate issue, should happen first)
 - [ ] Make detachable
 - [ ] Make closable by X button
 - [ ] Make resizable

### CODE REVIEW

**Comment by swati-maheshwari** [comment]
@pfrazee  How? does it work for webview?

**Comment by pfrazee** [comment]
@swati-maheshwari The solution we used is to switch to the `BrowserView` API instead of webviews, which work pretty differently. It basically comes automatically with browser views

**Comment by swati-maheshwari** [comment]
@pfrazee is there any solution for webview? to open docked debugtools

**Comment by pfrazee** [comment]
@swati-maheshwari sorry, I never solved that

**Pull request closed without merging**
