### PR TITLE
A few UI updates

### PR DESCRIPTION
**Pull request by taravancil**
Summary:

- Remove Dat contextual items from dropdown menu
- Live reloading is now in URL bar
- Swarm debugger updates in `beaker://library`

### CODE REVIEW

**Comment by pfrazee** [comment]
I love these updates, but I think we can't remove the contextual items until the sidebar is landed.

**Comment by taravancil** [comment]
Unless you think we should re-add the contextual items temporarily, I'm cool with waiting to merge this until we finish the sidebar.

**Comment by pfrazee** [comment]
Yep that's fine w/me

**Comment by pfrazee** [comment]
Yay can merge now

**Pull request merged**
