### PR TITLE
Upgrade FontAwesome to 5.5

### PR DESCRIPTION
**Pull request by Septimus**
TODO: Delete old FontAwesome files after 5.5 doesn't appear to have negative effects.

### CODE REVIEW

**Comment by Septimus** [comment]
Don't merge yet. Several icons are broken. Working through fixing them.

**Comment by Septimus** [comment]
Fixed most of the icons that I could see. There may be a few quick fixes as we notice random icons are messed up, but for the most part should be 👌

**Comment by pfrazee** [comment]
Any reason not to just delete the old FontAwesome assets?

**Comment by pfrazee** [comment]
A few issues still:

 - [ ] Icons missing in library-view (file icon in listing, toolbar in file-view)
 - [ ] Icons in the context-menu of the library are missing
 - [ ] Icons in the site menu dropdown are missing (in the toolbar, where View Source and Download as Zip are)
 - [ ] The positioning of the + icon in "New" in the builtin pages header (top right) is off
 - [ ] Icon spacing against the text in the builtin pages dropdown is off
 - [ ] "Create new from folder" icon is missing

After we've got these issues settled I'm going to do a pass on the aesthetics.

**Comment by Septimus** [comment]
* [ ]  Icons missing in library-view (file icon in listing, toolbar in file-view)
* [ ]  Icons in the context-menu of the library are missing
* [ ]  Icons in the site menu dropdown are missing (in the toolbar, where View Source and Download as Zip are)
* [ ]  The positioning of the + icon in "New" in the builtin pages header (top right) is off
* [ ]  Icon spacing against the text in the builtin pages dropdown is off
* [ ]  "Create new from folder" icon is missing

**Pull request closed without merging**
