### PR TITLE
Library usability tweaks

### PR DESCRIPTION
**Pull request by pfrazee**
A running PR of usability improvements, while I do QA

### CODE REVIEW

**Comment by pfrazee** [comment]
First: Add an "external link" icon to the title, so the user knows they can get to the site that way
screen shot 2017-06-24 at 1 36 04 pm

**Comment by pfrazee** [comment]
Second: Remove 'Edit site info' from dropdown
screen shot 2017-06-24 at 1 39 30 pm
screen shot 2017-06-24 at 1 39 37 pm

**Comment by pfrazee** [comment]
Third: Update the save/delete buttons to match the sidebar
screen shot 2017-06-24 at 1 42 39 pm
screen shot 2017-06-24 at 1 42 45 pm
screen shot 2017-06-24 at 1 45 09 pm
screen shot 2017-06-24 at 1 45 26 pm

**Comment by pfrazee** [comment]
Fourth: The read-only label was getting crowded with the external link icon.
screen shot 2017-06-24 at 1 47 54 pm

So I merged it with the disabled import files btn.

screen shot 2017-06-24 at 1 48 56 pm

**Comment by pfrazee** [comment]
When I first created a new site, the "Copy path" action was one of the more prominent, and my initial task was "Wait, I want to add files"

So, I moved it over to be an icon action next to the path
screen shot 2017-06-24 at 1 52 21 pm
screen shot 2017-06-24 at 1 55 53 pm

**Comment by pfrazee** [comment]
Before:
screen shot 2017-06-24 at 2 19 17 pm


After:
screen shot 2017-06-24 at 2 18 31 pm

**Comment by taravancil** [comment]
I updated the external link icon. @pfrazee wdyt?

library-title-hover

**Comment by pfrazee** [comment]
Simplified the left nav

screen shot 2017-06-24 at 8 52 50 pm

**Comment by taravancil** [comment]
I updated our `.message` styles. Here are`.success`, `.info`, `.primary`, and `.error` in that order (with mocked up copy).

screen shot 2017-06-24 at 9 27 46 pm

**Comment by pfrazee** [comment]
Great work. Moves forward the aesthetic.

One note: the "Restore" alert in that screenshot looks a bit low contrast.

**Comment by taravancil** [comment]
Yeah that one is definitely lower contrast than the rest. I'll tweak the
colors on that one today.

**Comment by pfrazee** [comment]
Im 👍  to merge this when you are

**Comment by taravancil** [comment]
Yeah, let's keep it open for a bit longer. I want to take one last pass.

**Pull request merged**
