### PR TITLE
Add 'Paste and Go' convenience item to location bar

### PR DESCRIPTION
**Pull request by composition4**
Took much longer than I expected for so few lines of code ('watch' isn't working for my system atm). Please review this and let me know if there are any glaring issues.

### CODE REVIEW

**Comment by composition4** [comment]
...none of these CI errors appear to be my fault... I'm not touching archives at all with a "Paste & Go" feature...
...Did I miss a merge?

**I hate you Travis** 😆

**Comment by pfrazee** [comment]
Nah our travis has been failing for a while. Not your PR's fault.

There is some changes I'll want to make to this. Easier for me to just make
and explain after.

On Thu, Nov 16, 2017 at 10:57 AM, Composition Fore <notifications@github.com

**Comment by composition4** [comment]
My apologies. Feel free to cherry-pick out e37a3910d200d4b1ab7c0f24f42df4d11e050b8f I'd forgotten to isolate that from this PR. 😕

**Comment by DTV96Calibre** [comment]
This one's been quiet for a while, did you ever get a chance to make changes? @pfrazee 
I can clean things up (merging and stuff) if you're busy with other things

**Comment by pfrazee** [comment]
Thanks for the reminder! Done. 1d9d483d99f08216df4ebe1876f0e0b8e9967e7a 😄

**Pull request closed without merging**
